### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by aayushborkar14** [Republic-of-Recklessness/nova-chrono#1]
- [x] Update README.md
- [x] Setup Firebase
- [x] Implement Backend
- [x] Write Security Rules
- [ ] Update UI
- [ ] Fix list ordering
- [ ] Initial Release
